import Foundation

/// The hidden trophies' art — one bespoke drawing each, no shared base.
///
/// Separate from `TrophyArt` in every sense. A composed badge says *this is
/// one of the set*, and a hidden trophy has spent its whole life so far as a
/// grey question mark: the moment it turns over is the one moment it gets, so
/// it is worth a picture that owes nothing to a frame.
///
/// They are also where the detail budget goes. A composed badge spends most of
/// its 1,024 cells on a frame shared with twenty-two others and draws its
/// subject in 144; these draw theirs in all of them, at up to four times the
/// pixels of any mascot in the app.
public enum TrophyArtHidden {

    /// A house with the radar on in the window.
    public static let homeTeam = Sprite([
        "................................",
        "................................",
        "................................",
        "...............kk...............",
        "..............krrk..............",
        ".............krrrrk...kkk.......",
        "............krrrrrrk..kxk.......",
        "...........krrrrrrrrk.kxk.......",
        "..........krrrrrrrrrrkkxk.......",
        ".........krrrrrrrrrrrrkkk.......",
        "........krrrrrrrrrrrrrrk........",
        ".......krrrrrrrrrrrrrrrrk.......",
        "......krrrrrrrrrrrrrrrrrrk......",
        ".....krrrrrrrrrrrrrrrrrrrrk.....",
        "....krrrrrrrrrrrrrrrrrrrrrrk....",
        "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
        ".....kcccccccccccccccccccck.....",
        ".....kcccccccccccccccccccck.....",
        ".....kccttttttttcccccccccck.....",
        ".....kcctuuuuuutcccccccccck.....",
        ".....kcctuuuuwutcctttttttck.....",
        ".....kcctuffwuutcctzzzzztck.....",
        ".....kcctufffuutcctzzzzztck.....",
        ".....kcctufffuutcctzzzzztck.....",
        ".....kcctuuuuuutcctzzzzztck.....",
        ".....kccttttttttcctzzzoztck.....",
        ".....kcccccccccccctzzzzztck.....",
        ".....kcccccccccccctzzzzztck.....",
        ".....kkkkkkkkkkkkktzzzzztkk.....",
        "................................",
        "................................",
        "................................",
    ])

    /// A glass held over somebody else's diff.
    public static let peerReview = Sprite([
        "................................",
        "................................",
        "................................",
        "................................",
        "..................kkkkk.........",
        "................kkeeeeekk.......",
        "..ttttttttttttkkeekkkkkeekk.....",
        "..tcccccccccckeekkuuuuukkeek....",
        "..tccfccccccckekuuwwwwwuukek....",
        "..tccffcmmmmkekuuwwwwwwwuukek...",
        "..tccfcccccckekuwccwwwwwwukek...",
        "..tccfccccckekuwwcwwwwwwwwukek..",
        "..tccffcmmmkekuwwwwwwwwwwwukek..",
        "..tccfccccckekuwwwwwwwwwwwukek..",
        "..tcccccccckekuwwwwwwwwwwwukek..",
        "..tccrrcmmmkekuwwwwwwwwwwwukek..",
        "..tccccccccckekuwwwwwwwwwukek...",
        "..tccfcccccckekuuwwwwwwwuukek...",
        "..tccffcmmmmmkekuuwwwwwuukek....",
        "..tccfccccccckeekkuuuuukkeek....",
        "..tccccccccccckkeekkkkkeekk.....",
        "..tccrrcmmmmmmmmkkeeeeekktkzk...",
        "..tccccccccccccccckkkkkcctkzk...",
        "..tccfccccccccccccccccccct.kzk..",
        "..tccffcmmmmmmmcccccccccct.kzk..",
        "..tccfccccccccccccccccccct..kzk.",
        "..tcccccccccccccccccccccct..kzk.",
        "..tcccccccccccccccccccccct......",
        "..tcccccccccccccccccccccct......",
        "..tttttttttttttttttttttttt......",
        "................................",
        "................................",
    ])

    /// An arrow all the way round, back to where it started.
    public static let fullCircle = Sprite([
        "................................",
        "................................",
        "................................",
        "...........k....................",
        ".........kku...........k........",
        ".......kkuuu.......k...ukk......",
        "......kkuuuuu.......k.uuukk.....",
        ".....kkuuuuuu.......ukuuuukk....",
        ".....kuuuuukkk......uukuukuk....",
        "....kuuuuukk........uuukkuuuk...",
        "....kuuuukk...kkkkk.uuukkuuuk...",
        "...kuuuukk...kccccckuukuukuuuk..",
        "...kuuuuk...kccccccckk..kuuuuk..",
        "...uuuukk..kccccccmcck..kkuuuu..",
        "..kuuuuk..kccccccmcccck..kuuuuk.",
        "..kuuuuk..kccccfffcccck..kuuuuk.",
        "..kuuuuk..kccccfffcccck..kuuuuk.",
        "..kuuuuk..kccccfffcccck..kuuuuk.",
        "..kuuuuk..kccccccccccck..kuuuuk.",
        "...uuuukk..kccccccccck..kkuuuu..",
        "...kuuuuk...kccccccck...kuuuuk..",
        "...kuuuukk...kccccck...kkuuuuk..",
        "....kuuuukk...kkkkk...kkuuuuk...",
        "....kuuuuukk.........kkuuuuuk...",
        ".....kuuuuukkk.....kkkuuuuuk....",
        ".....kkuuuuuukkkkkkkuuuuuukk....",
        "......kkuuuuuuuuuuuuuuuuukk.....",
        ".......kkuuuuuuuuuuuuuuukk......",
        ".........kkuuuuuuuuuuukk........",
        "...........kkuuuuuuukk..........",
        "..............kkkkk.............",
        "................................",
    ])

    /// A number, and the line it reads the same across.
    public static let palindrome = Sprite([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        ".kttttttttttttttttttttttttttttk.",
        ".ktttttttttttttyytttttttttttttk.",
        ".kttttttttttttttttttttttttttttk.",
        ".ktttttttttttttyytttttttttttttk.",
        ".kttttttttttttttttttttttttttttk.",
        ".ktttctttttccctyytccctttttctttk.",
        ".kttccttttctttcttctttctttcctttk.",
        ".ktttcttttttttcyyttttcttttctttk.",
        ".ktttctttttttcttttttctttttctttk.",
        ".ktttcttttttcttyyttcttttttctttk.",
        ".ktttctttttcttttttctttttttctttk.",
        ".kttccctttcccccyyccccctttcccttk.",
        ".kttttttttttttttttttttttttttttk.",
        ".ktttttttttttttyytttttttttttttk.",
        ".kttttttttttttttttttttttttttttk.",
        ".ktttttttttttttyytttttttttttttk.",
        ".kttttttttttttttttttttttttttttk.",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    /// Scales, dead level. Everything added was taken away again.
    public static let zeroSum = Sprite([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "..............kook..............",
        "..............oooo..............",
        "....kkkkkkkkkkkkkkkkkkkkkkkk....",
        "....nnnnnnnnnnnnnnnnnnnnnnnn....",
        ".....f....................m.....",
        ".....f.........ko.........m.....",
        "...fffff.......ko.......rrrrr...",
        ".....f.........ko.........m.....",
        ".kkkkkkkkk.....ko.....kkkkkkkkk.",
        "..knnnnnk......ko......knnnnnk..",
        "....kkk........ko........kkk....",
        "...............ko...............",
        "...............ko...............",
        "...............ko...............",
        "...............ko...............",
        "...............ko...............",
        "...............ko...............",
        "..........kkkkkkkkkkkk..........",
        "..........knnnnnnnnnnk..........",
        "..........kkkkkkkkkkkk..........",
        "................................",
        "................................",
    ])

    /// A merry-go-round, going round.
    public static let carousel = Sprite([
        "..............ooooo.............",
        "...............kk...............",
        "................................",
        "...kcccccccccccccccccccccccck...",
        ".....krrrrrrrrrrrrrrrrrrrrk.....",
        ".......kcccccccccccccccck.......",
        ".........krrrrrrrrrrrrk.........",
        "...........kcccccccck...........",
        ".............krrrrk.............",
        "...............kk...............",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "...kcckkcckkcckkcckkcckkcckkcck.",
        "....kk..kk..kk..kk..kk..kk..kk..",
        ".......me.......me.......me.....",
        ".......me.......me.......me.....",
        "......kkk......kkk......kkk.....",
        ".....kuuuk....kyyyk....kfffk....",
        "....kuwuuuk..kywyyyk..kfwfffk...",
        "....kuuuuuk..kyyyyyk..kfffffk...",
        "....kuuuuuk..kyyyyyk..kfffffk...",
        ".....kuuuk....kyyyk....kfffk....",
        "......kkk......kkk......kkk.....",
        ".......me.......me.......me.....",
        ".......me.......me.......me.....",
        ".......me.......me.......me.....",
        ".......me.......me.......me.....",
        ".......me.......me.......me.....",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "..knnnnnnnnnnnnnnnnnnnnnnnnnnk..",
        "....kkkkkkkkkkkkkkkkkkkkkkkk....",
        "................................",
        "................................",
    ])

    /// A screen with a badge parked in every corner of it.
    public static let fourCorners = Sprite([
        "................................",
        "................................",
        "................................",
        "................................",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "..kttttttttttttttttttttttttttk..",
        "..kttttttttttttttttttttttttttk..",
        "..kttkkkkkuuuuuuuuuuuukkkkkttk..",
        "..kttkoookuuuuuuuuuuuukoookttk..",
        "..kttkonokuuuuuuuuuuuukonokttk..",
        "..kttkoookuuuuuuuuuuuukoookttk..",
        "..kttkkkkkuuuuuuuuuuuukkkkkttk..",
        "..kttuuuuuuuuuuuuuuuuuuuuuuttk..",
        "..kttuuuuuuuuuuuuuuuuuuuuuuttk..",
        "..kttuuuuuuuuuuuuuuuuuuuuuuttk..",
        "..kttuuuuuuuuuuuuuuuuuuuuuuttk..",
        "..kttuuuuuuuuuuuuuuuuuuuuuuttk..",
        "..kttkkkkkuuuuuuuuuuuukkkkkttk..",
        "..kttkoookuuuuuuuuuuuukoookttk..",
        "..kttkonokuuuuuuuuuuuukonokttk..",
        "..kttkoookuuuuuuuuuuuukoookttk..",
        "..kttkkkkkuuuuuuuuuuuukkkkkttk..",
        "..kttttttttttttttttttttttttttk..",
        "..kttttttttttttttttttttttttttk..",
        "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
        "............kkkkkkkk............",
        "............knnnnnnk............",
        "............knnnnnnk............",
        "........kkkkkkkkkkkkkkkk........",
        "........kkkkkkkkkkkkkkkk........",
        "................................",
        "................................",
    ])
}
